#!/bin/sh

CONFIG_DIR="$1"
file="/tmp/state.json"

[ "${DEBUG}" = 'true' ] && set -x

./folders2consul_json.py from-folders "${CONFIG_DIR}" "${file}" &&
  consul kv import "@${file}" &&
  rm "${file}"
